FUNCTION ZMAP2E_RESBDGET_TO_COMP_DETAIL.
*"--------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(RESBDGET) LIKE  RESBDGET STRUCTURE  RESBDGET
*"  CHANGING
*"     REFERENCE(BAPI_NETWORK_COMP_DETAIL)
*"  LIKE  BAPI_NETWORK_COMP_DETAIL STRUCTURE  BAPI_NETWORK_COMP_DETAIL
*"--------------------------------------------------------------------

* This function module was generated. Don't change it manually!
* <VERSION>|5
* <BAPI_STRUCTURE>|BAPI_NETWORK_COMP_DETAIL
* <SAP_STRUCTURE>|RESBDGET
* <INTERN_TO_EXTERN>|X
* <APPEND FORM>|X

* <BAPI_FIELD>|CUSTOMER
* <SAP_FIELD>|KUNNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KUNNR
  TO BAPI_NETWORK_COMP_DETAIL-CUSTOMER                            .

* <BAPI_FIELD>|SUPP_VENDOR
* <SAP_FIELD>|EMLIF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-EMLIF
  TO BAPI_NETWORK_COMP_DETAIL-SUPP_VENDOR                         .

* <BAPI_FIELD>|ADDR_NO2
* <SAP_FIELD>|ADRN2
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ADRN2
  TO BAPI_NETWORK_COMP_DETAIL-ADDR_NO2                            .

* <BAPI_FIELD>|ADDR_NO
* <SAP_FIELD>|ADRNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ADRNR
  TO BAPI_NETWORK_COMP_DETAIL-ADDR_NO                             .

* <BAPI_FIELD>|ORIGINAL_QUANTITY
* <SAP_FIELD>|NOMNG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-NOMNG
  TO BAPI_NETWORK_COMP_DETAIL-ORIGINAL_QUANTITY                   .

* <BAPI_FIELD>|VSI_NO
* <SAP_FIELD>|ROANZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ROANZ
  TO BAPI_NETWORK_COMP_DETAIL-VSI_NO                              .

* <BAPI_FIELD>|MANUAL_REQUIREMENTS_DATE
* <SAP_FIELD>|KZMPF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KZMPF
  TO BAPI_NETWORK_COMP_DETAIL-MANUAL_REQUIREMENTS_DATE            .

* <BAPI_FIELD>|VSI_FORMULA
* <SAP_FIELD>|RFORM
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-RFORM
  TO BAPI_NETWORK_COMP_DETAIL-VSI_FORMULA                         .

* <BAPI_FIELD>|VSI_QTY
* <SAP_FIELD>|ROMEN
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ROMEN
  TO BAPI_NETWORK_COMP_DETAIL-VSI_QTY                             .

* <BAPI_FIELD>|VSI_SIZE3
* <SAP_FIELD>|ROMS3
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ROMS3
  TO BAPI_NETWORK_COMP_DETAIL-VSI_SIZE3                           .

* <BAPI_FIELD>|VSI_SIZE2
* <SAP_FIELD>|ROMS2
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ROMS2
  TO BAPI_NETWORK_COMP_DETAIL-VSI_SIZE2                           .

* <BAPI_FIELD>|VSI_SIZE1
* <SAP_FIELD>|ROMS1
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ROMS1
  TO BAPI_NETWORK_COMP_DETAIL-VSI_SIZE1                           .

* <BAPI_FIELD>|WITHDRAWN
* <SAP_FIELD>|KZEAR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KZEAR
  TO BAPI_NETWORK_COMP_DETAIL-WITHDRAWN                           .

* <BAPI_FIELD>|BULK_MAT
* <SAP_FIELD>|SCHGT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-SCHGT
  TO BAPI_NETWORK_COMP_DETAIL-BULK_MAT                            .

* <BAPI_FIELD>|BACKFLUSH
* <SAP_FIELD>|RGEKZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-RGEKZ
  TO BAPI_NETWORK_COMP_DETAIL-BACKFLUSH                           .

* <BAPI_FIELD>|SORT_STRING
* <SAP_FIELD>|SORTF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-SORTF
  TO BAPI_NETWORK_COMP_DETAIL-SORT_STRING                         .

* <BAPI_FIELD>|UNLOAD_PT
* <SAP_FIELD>|ABLAD
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-ABLAD
  TO BAPI_NETWORK_COMP_DETAIL-UNLOAD_PT                           .

* <BAPI_FIELD>|TRACKINGNO
* <SAP_FIELD>|BEDNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-BEDNR
  TO BAPI_NETWORK_COMP_DETAIL-TRACKINGNO                          .

* <BAPI_FIELD>|WITHD_QUAN
* <SAP_FIELD>|DENMNG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-DENMNG
  TO BAPI_NETWORK_COMP_DETAIL-WITHD_QUAN                          .

* <BAPI_FIELD>|SPECIAL_STOCK
* <SAP_FIELD>|SOBKZ_D
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-SOBKZ_D
  TO BAPI_NETWORK_COMP_DETAIL-SPECIAL_STOCK                       .

* <BAPI_FIELD>|RES_ITEM
* <SAP_FIELD>|RSPOS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-RSPOS
  TO BAPI_NETWORK_COMP_DETAIL-RES_ITEM                            .

* <BAPI_FIELD>|RESERV_NO
* <SAP_FIELD>|RSNUM
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-RSNUM
  TO BAPI_NETWORK_COMP_DETAIL-RESERV_NO                           .

* <BAPI_FIELD>|REQUIREMENTS_PLAN_NO
* <SAP_FIELD>|PBDNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-PBDNR
  TO BAPI_NETWORK_COMP_DETAIL-REQUIREMENTS_PLAN_NO                .

* <BAPI_FIELD>|PURCHASE_ORDER_EXISTS
* <SAP_FIELD>|FLG_PURS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-FLG_PURS
  TO BAPI_NETWORK_COMP_DETAIL-PURCHASE_ORDER_EXISTS               .

* <BAPI_FIELD>|PS_TEXT_TYPE
* <SAP_FIELD>|PSTXTAR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-PSTXTAR
  TO BAPI_NETWORK_COMP_DETAIL-PS_TEXT_TYPE                        .

* <BAPI_FIELD>|PS_TEXT_DESCRIPTION
* <SAP_FIELD>|PSTXTTI
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-PSTXTTI
  TO BAPI_NETWORK_COMP_DETAIL-PS_TEXT_DESCRIPTION                 .

* <BAPI_FIELD>|PREQ_ITEM
* <SAP_FIELD>|BNFPO
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
*MOVE RESBDGET-BNFPO
MOVE RESBDGET-BANFPO
  TO BAPI_NETWORK_COMP_DETAIL-PREQ_ITEM                           .

* <BAPI_FIELD>|PREQ_NO
* <SAP_FIELD>|BANFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-BANFNR
  TO BAPI_NETWORK_COMP_DETAIL-PREQ_NO                             .

* <BAPI_FIELD>|PHANT_ITEM
* <SAP_FIELD>|DUMPS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-DUMPS
  TO BAPI_NETWORK_COMP_DETAIL-PHANT_ITEM                          .

* <BAPI_FIELD>|MOVE_TYPE
* <SAP_FIELD>|BWART
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-BWART
  TO BAPI_NETWORK_COMP_DETAIL-MOVE_TYPE                           .

* <BAPI_FIELD>|GOODS_RECEIVED_QUAN
* <SAP_FIELD>|WEMNG_CMP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-WEMNG_CMP
  TO BAPI_NETWORK_COMP_DETAIL-GOODS_RECEIVED_QUAN                 .

* <BAPI_FIELD>|COMMITED_QUAN
* <SAP_FIELD>|DVMENG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-DVMENG
  TO BAPI_NETWORK_COMP_DETAIL-COMMITED_QUAN                       .

* <BAPI_FIELD>|S_ORD_ITEM
* <SAP_FIELD>|KDPOS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KDPOS
  TO BAPI_NETWORK_COMP_DETAIL-S_ORD_ITEM                          .

* <BAPI_FIELD>|SALES_ORD
* <SAP_FIELD>|KDAUF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KDAUF
  TO BAPI_NETWORK_COMP_DETAIL-SALES_ORD                           .

* <BAPI_FIELD>|WBS_ELEMENT
* <SAP_FIELD>|PSPEL
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-PSPEL
  TO BAPI_NETWORK_COMP_DETAIL-WBS_ELEMENT                         .

* <BAPI_FIELD>|DELIVERY_DAYS
* <SAP_FIELD>|LIFZT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-LIFZT
  TO BAPI_NETWORK_COMP_DETAIL-DELIVERY_DAYS                       .

* <BAPI_FIELD>|BOMEXPL_NO
* <SAP_FIELD>|SERNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-SERNR
  TO BAPI_NETWORK_COMP_DETAIL-BOMEXPL_NO                          .

* <BAPI_FIELD>|BATCH
* <SAP_FIELD>|CHARG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-CHARG
  TO BAPI_NETWORK_COMP_DETAIL-BATCH                               .

* <BAPI_FIELD>|STGE_LOC
* <SAP_FIELD>|LGORT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-LGORT
  TO BAPI_NETWORK_COMP_DETAIL-STGE_LOC                            .

* <BAPI_FIELD>|COST_RELEVANT
* <SAP_FIELD>|SANKA
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-SANKA
  TO BAPI_NETWORK_COMP_DETAIL-COST_RELEVANT                       .

* <BAPI_FIELD>|MRP_DISTRIBUTION_KEY
* <SAP_FIELD>|VERTI
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-VERTI
  TO BAPI_NETWORK_COMP_DETAIL-MRP_DISTRIBUTION_KEY                .

* <BAPI_FIELD>|LEAD_TIME_OFFSET_OPR
* <SAP_FIELD>|NLFZV
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-NLFZV
  TO BAPI_NETWORK_COMP_DETAIL-LEAD_TIME_OFFSET_OPR                .

* <BAPI_FIELD>|REQ_DATE
* <SAP_FIELD>|BDTER
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-BDTER
  TO BAPI_NETWORK_COMP_DETAIL-REQ_DATE                            .

* <BAPI_FIELD>|MRP_RELEVANT
* <SAP_FIELD>|AUDISP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-AUDISP
  TO BAPI_NETWORK_COMP_DETAIL-MRP_RELEVANT                        .

* <BAPI_FIELD>|ITEM_TEXT
* <SAP_FIELD>|POTX1
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-POTX1
  TO BAPI_NETWORK_COMP_DETAIL-ITEM_TEXT                           .

* <BAPI_FIELD>|ITEM_CAT
* <SAP_FIELD>|POSTP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-POSTP
  TO BAPI_NETWORK_COMP_DETAIL-ITEM_CAT                            .

* <BAPI_FIELD>|PLANT
* <SAP_FIELD>|WERKS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-WERKS
  TO BAPI_NETWORK_COMP_DETAIL-PLANT                               .

* <BAPI_FIELD>|MATL_DESC
* <SAP_FIELD>|MATXT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-MATXT
  TO BAPI_NETWORK_COMP_DETAIL-MATL_DESC                           .

* <BAPI_FIELD>|MATERIAL
* <SAP_FIELD>|MATNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-MATNR
  TO BAPI_NETWORK_COMP_DETAIL-MATERIAL_LONG                            .

* <BAPI_FIELD>|ITEM_NUMBER
* <SAP_FIELD>|POSNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-POSNR
  TO BAPI_NETWORK_COMP_DETAIL-ITEM_NUMBER                         .

* <BAPI_FIELD>|NETWORK
* <SAP_FIELD>|AUFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-AUFNR
  TO BAPI_NETWORK_COMP_DETAIL-NETWORK                             .

* <BAPI_FIELD>|ACTIVITY
* <SAP_FIELD>|VORNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-VORNR
  TO BAPI_NETWORK_COMP_DETAIL-ACTIVITY                            .

* <BAPI_FIELD>|GL_ACCOUNT
* <SAP_FIELD>|SAKNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-SAKNR
  TO BAPI_NETWORK_COMP_DETAIL-GL_ACCOUNT                          .

* <BAPI_FIELD>|VENDOR_NO
* <SAP_FIELD>|LIFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-LIFNR
  TO BAPI_NETWORK_COMP_DETAIL-VENDOR_NO                           .

* <BAPI_FIELD>|AGMT_ITEM
* <SAP_FIELD>|KTPNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KTPNR
  TO BAPI_NETWORK_COMP_DETAIL-AGMT_ITEM                           .

* <BAPI_FIELD>|AGREEMENT
* <SAP_FIELD>|KONNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KONNR
  TO BAPI_NETWORK_COMP_DETAIL-AGREEMENT                           .

* <BAPI_FIELD>|PUR_INFO_RECORD_DATA_FIXED
* <SAP_FIELD>|KZFIX
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-KZFIX
  TO BAPI_NETWORK_COMP_DETAIL-PUR_INFO_RECORD_DATA_FIXED          .

* <BAPI_FIELD>|GR_PR_TIME
* <SAP_FIELD>|WEBAZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-WEBAZ
  TO BAPI_NETWORK_COMP_DETAIL-GR_PR_TIME                          .

* <BAPI_FIELD>|MATL_GROUP
* <SAP_FIELD>|MATKL
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-MATKL
  TO BAPI_NETWORK_COMP_DETAIL-MATL_GROUP                          .

* <BAPI_FIELD>|PREQ_NAME
* <SAP_FIELD>|AFNAM
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-AFNAM
  TO BAPI_NETWORK_COMP_DETAIL-PREQ_NAME                           .

* <BAPI_FIELD>|GR_RCPT
* <SAP_FIELD>|WEMPF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-WEMPF
  TO BAPI_NETWORK_COMP_DETAIL-GR_RCPT                             .

* <BAPI_FIELD>|PRICE_UNIT
* <SAP_FIELD>|PEINH
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-PEINH
  TO BAPI_NETWORK_COMP_DETAIL-PRICE_UNIT                          .

* <BAPI_FIELD>|PRICE
* <SAP_FIELD>|GPREIS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
* ^_nt_1134594
*MOVE RESBDGET-GPREIS
*  TO BAPI_NETWORK_COMP_DETAIL-PRICE                               .
data: l_amount type BAPICURR-BAPICURR.
CALL FUNCTION 'CNIF_CONVERT_CURRENCY2EXT'
  EXPORTING
    I_CURRENCY       = RESBDGET-WAERS
    I_AMOUNT         = RESBDGET-GPREIS
*   I_DECIMALS       = 2
  IMPORTING
    E_AMOUNT         = l_amount
          .
if l_amount < '10000000000000.00'.
  move l_amount to BAPI_NETWORK_COMP_DETAIL-PRICE.
else.
  MOVE RESBDGET-GPREIS
    TO BAPI_NETWORK_COMP_DETAIL-PRICE                               .
endif.
* v_nt_1134594

* <BAPI_FIELD>|INFO_REC
* <SAP_FIELD>|INFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-INFNR
  TO BAPI_NETWORK_COMP_DETAIL-INFO_REC                            .

* <BAPI_FIELD>|PURCH_ORG
* <SAP_FIELD>|EKORG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-EKORG
  TO BAPI_NETWORK_COMP_DETAIL-PURCH_ORG                           .

* <BAPI_FIELD>|PUR_GROUP
* <SAP_FIELD>|EKGRP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-EKGRP
  TO BAPI_NETWORK_COMP_DETAIL-PUR_GROUP                           .

* <BAPI_FIELD>|CONFIGURED
* <SAP_FIELD>|KZKFG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE RESBDGET-kzkfg
  TO BAPI_NETWORK_COMP_DETAIL-CONFIGURED.

* <BAPI_FIELD>|CURRENCY_ISO
* <SAP_FIELD>|WAERS
* <CODE_PART>|ISO_INT_CURR
* <ADD_FIELD>|CURRENCY
MOVE RESBDGET-WAERS
  TO BAPI_NETWORK_COMP_DETAIL-CURRENCY                            .
IF NOT
RESBDGET-WAERS
IS INITIAL.
  CALL FUNCTION 'CURRENCY_CODE_SAP_TO_ISO'
       EXPORTING
            SAP_CODE  =
       RESBDGET-WAERS
       IMPORTING
            ISO_CODE  =
       BAPI_NETWORK_COMP_DETAIL-CURRENCY_ISO
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
  CLEAR BAPI_NETWORK_COMP_DETAIL-CURRENCY_ISO                        .
  ENDIF.
ELSE.
  CLEAR BAPI_NETWORK_COMP_DETAIL-CURRENCY_ISO                        .
ENDIF.

* <BAPI_FIELD>|BASE_UOM_ISO
* <SAP_FIELD>|MEINS
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|BASE_UOM
MOVE RESBDGET-MEINS
  TO BAPI_NETWORK_COMP_DETAIL-BASE_UOM                            .
IF NOT
RESBDGET-MEINS
IS INITIAL.
  CALL FUNCTION 'UNIT_OF_MEASURE_SAP_TO_ISO'
       EXPORTING
            SAP_CODE    =
       RESBDGET-MEINS
       IMPORTING
            ISO_CODE    =
       BAPI_NETWORK_COMP_DETAIL-BASE_UOM_ISO
       EXCEPTIONS
            NOT_FOUND   = 1
            NO_ISO_CODE = 2
            OTHERS      = 3.
  IF SY-SUBRC <> 0.
  CLEAR BAPI_NETWORK_COMP_DETAIL-BASE_UOM_ISO                        .
  ENDIF.
ELSE.
  CLEAR BAPI_NETWORK_COMP_DETAIL-BASE_UOM_ISO                        .
ENDIF.

* <BAPI_FIELD>|VSI_SIZE_UNIT_ISO
* <SAP_FIELD>|ROMEI
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|VSI_SIZE_UNIT
MOVE RESBDGET-ROMEI
  TO BAPI_NETWORK_COMP_DETAIL-VSI_SIZE_UNIT                       .
IF NOT
RESBDGET-ROMEI
IS INITIAL.
  CALL FUNCTION 'UNIT_OF_MEASURE_SAP_TO_ISO'
       EXPORTING
            SAP_CODE    =
       RESBDGET-ROMEI
       IMPORTING
            ISO_CODE    =
       BAPI_NETWORK_COMP_DETAIL-VSI_SIZE_UNIT_ISO
       EXCEPTIONS
            NOT_FOUND   = 1
            NO_ISO_CODE = 2
            OTHERS      = 3.
  IF SY-SUBRC <> 0.
  CLEAR BAPI_NETWORK_COMP_DETAIL-VSI_SIZE_UNIT_ISO                   .
  ENDIF.
ELSE.
  CLEAR BAPI_NETWORK_COMP_DETAIL-VSI_SIZE_UNIT_ISO                   .
ENDIF.

* <BAPI_FIELD>|GOODS_RECEIVED_QUAN_UNIT_ISO
* <SAP_FIELD>|EINHEIT
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|GOODS_RECEIVED_QUAN_UNIT
MOVE RESBDGET-EINHEIT
  TO BAPI_NETWORK_COMP_DETAIL-GOODS_RECEIVED_QUAN_UNIT            .
IF NOT
RESBDGET-EINHEIT
IS INITIAL.
  CALL FUNCTION 'UNIT_OF_MEASURE_SAP_TO_ISO'
       EXPORTING
            SAP_CODE    =
       RESBDGET-EINHEIT
       IMPORTING
            ISO_CODE    =
       BAPI_NETWORK_COMP_DETAIL-GOODS_RECEIVED_QUAN_UNIT_ISO
       EXCEPTIONS
            NOT_FOUND   = 1
            NO_ISO_CODE = 2
            OTHERS      = 3.
  IF SY-SUBRC <> 0.
  CLEAR BAPI_NETWORK_COMP_DETAIL-GOODS_RECEIVED_QUAN_UNIT_ISO        .
  ENDIF.
ELSE.
  CLEAR BAPI_NETWORK_COMP_DETAIL-GOODS_RECEIVED_QUAN_UNIT_ISO        .
ENDIF.

* <BAPI_FIELD>|LEAD_TIME_OFFSET_OPR_UNIT_ISO
* <SAP_FIELD>|NLFMV
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|LEAD_TIME_OFFSET_OPR_UNIT
MOVE RESBDGET-NLFMV
  TO BAPI_NETWORK_COMP_DETAIL-LEAD_TIME_OFFSET_OPR_UNIT           .
IF NOT
RESBDGET-NLFMV
IS INITIAL.
  CALL FUNCTION 'UNIT_OF_MEASURE_SAP_TO_ISO'
       EXPORTING
            SAP_CODE    =
       RESBDGET-NLFMV
       IMPORTING
            ISO_CODE    =
       BAPI_NETWORK_COMP_DETAIL-LEAD_TIME_OFFSET_OPR_UNIT_ISO
       EXCEPTIONS
            NOT_FOUND   = 1
            NO_ISO_CODE = 2
            OTHERS      = 3.
  IF SY-SUBRC <> 0.
  CLEAR BAPI_NETWORK_COMP_DETAIL-LEAD_TIME_OFFSET_OPR_UNIT_ISO       .
  ENDIF.
ELSE.
  CLEAR BAPI_NETWORK_COMP_DETAIL-LEAD_TIME_OFFSET_OPR_UNIT_ISO       .
ENDIF.

* <BAPI_FIELD>|VAR_SIZE_COMP_MEASURE_UNIT_ISO
* <SAP_FIELD>|ROKME
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|VAR_SIZE_COMP_MEASURE_UNIT
MOVE RESBDGET-ROKME
  TO BAPI_NETWORK_COMP_DETAIL-VAR_SIZE_COMP_MEASURE_UNIT          .
IF NOT
RESBDGET-ROKME
IS INITIAL.
  CALL FUNCTION 'UNIT_OF_MEASURE_SAP_TO_ISO'
       EXPORTING
            SAP_CODE    =
       RESBDGET-ROKME
       IMPORTING
            ISO_CODE    =
       BAPI_NETWORK_COMP_DETAIL-VAR_SIZE_COMP_MEASURE_UNIT_ISO
       EXCEPTIONS
            NOT_FOUND   = 1
            NO_ISO_CODE = 2
            OTHERS      = 3.
  IF SY-SUBRC <> 0.
  CLEAR BAPI_NETWORK_COMP_DETAIL-VAR_SIZE_COMP_MEASURE_UNIT_ISO      .
  ENDIF.
ELSE.
  CLEAR BAPI_NETWORK_COMP_DETAIL-VAR_SIZE_COMP_MEASURE_UNIT_ISO      .
ENDIF.

PERFORM MAP2E_RESBDGET_TO_COMP_DETAIL
  USING
    RESBDGET
  CHANGING
    BAPI_NETWORK_COMP_DETAIL      .





ENDFUNCTION.

FORM MAP2E_RESBDGET_TO_COMP_DETAIL
  USING
    RESBDGET
    STRUCTURE RESBDGET
  CHANGING
    BAPI_NETWORK_COMP_DETAIL
    STRUCTURE BAPI_NETWORK_COMP_DETAIL      .
  data: begin of component,
         rsnum like resbd-rsnum,
         rspos like resbd-rspos,
         rsart like resbd-rsart,
  end of component.

  component-rsnum = resbdget-rsnum.
  component-rspos = resbdget-rspos.
  component-rsart = resbdget-rsart.
  move component to bapi_network_comp_detail-component.
* Bedarfsmenge
  if resbdget-shkzg = soll.
   bapi_network_comp_detail-entry_quantity = resbdget-bdmng * ( -1 ).
  elseif resbdget-shkzg = haben.
   bapi_network_comp_detail-entry_quantity = resbdget-bdmng.
  endif.
* Löschkennzeichen
  move resbdget-xloek
    to bapi_network_comp_detail-deletion_flag.

ENDFORM.
